// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 25},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
	}
	// ServiceVersionsColumns holds the columns for the "service_versions" table.
	ServiceVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt},
		{Name: "config", Type: field.TypeString},
		{Name: "service_service_versions", Type: field.TypeUUID, Nullable: true},
	}
	// ServiceVersionsTable holds the schema information for the "service_versions" table.
	ServiceVersionsTable = &schema.Table{
		Name:       "service_versions",
		Columns:    ServiceVersionsColumns,
		PrimaryKey: []*schema.Column{ServiceVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "service_versions_services_serviceVersions",
				Columns:    []*schema.Column{ServiceVersionsColumns[3]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServicesTable,
		ServiceVersionsTable,
	}
)

func init() {
	ServiceVersionsTable.ForeignKeys[0].RefTable = ServicesTable
}
