// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entproject/ent/service"
	"entproject/ent/serviceversion"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ServiceVersion is the model entity for the ServiceVersion schema.
type ServiceVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Config holds the value of the "config" field.
	Config string `json:"config,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServiceVersionQuery when eager-loading is set.
	Edges                    ServiceVersionEdges `json:"edges"`
	service_service_versions *uuid.UUID
}

// ServiceVersionEdges holds the relations/edges for other nodes in the graph.
type ServiceVersionEdges struct {
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServiceVersionEdges) ServiceOrErr() (*Service, error) {
	if e.loadedTypes[0] {
		if e.Service == nil {
			// The edge service was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: service.Label}
		}
		return e.Service, nil
	}
	return nil, &NotLoadedError{edge: "service"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServiceVersion) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceversion.FieldID, serviceversion.FieldVersion:
			values[i] = new(sql.NullInt64)
		case serviceversion.FieldConfig:
			values[i] = new(sql.NullString)
		case serviceversion.ForeignKeys[0]: // service_service_versions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type ServiceVersion", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServiceVersion fields.
func (sv *ServiceVersion) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sv.ID = int(value.Int64)
		case serviceversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				sv.Version = int(value.Int64)
			}
		case serviceversion.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				sv.Config = value.String
			}
		case serviceversion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field service_service_versions", values[i])
			} else if value.Valid {
				sv.service_service_versions = new(uuid.UUID)
				*sv.service_service_versions = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryService queries the "service" edge of the ServiceVersion entity.
func (sv *ServiceVersion) QueryService() *ServiceQuery {
	return (&ServiceVersionClient{config: sv.config}).QueryService(sv)
}

// Update returns a builder for updating this ServiceVersion.
// Note that you need to call ServiceVersion.Unwrap() before calling this method if this ServiceVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (sv *ServiceVersion) Update() *ServiceVersionUpdateOne {
	return (&ServiceVersionClient{config: sv.config}).UpdateOne(sv)
}

// Unwrap unwraps the ServiceVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sv *ServiceVersion) Unwrap() *ServiceVersion {
	tx, ok := sv.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServiceVersion is not a transactional entity")
	}
	sv.config.driver = tx.drv
	return sv
}

// String implements the fmt.Stringer.
func (sv *ServiceVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ServiceVersion(")
	builder.WriteString(fmt.Sprintf("id=%v", sv.ID))
	builder.WriteString(", version=")
	builder.WriteString(fmt.Sprintf("%v", sv.Version))
	builder.WriteString(", config=")
	builder.WriteString(sv.Config)
	builder.WriteByte(')')
	return builder.String()
}

// ServiceVersions is a parsable slice of ServiceVersion.
type ServiceVersions []*ServiceVersion

func (sv ServiceVersions) config(cfg config) {
	for _i := range sv {
		sv[_i].config = cfg
	}
}
