// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"entproject/ent/predicate"
	"entproject/ent/serviceversion"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceVersionDelete is the builder for deleting a ServiceVersion entity.
type ServiceVersionDelete struct {
	config
	hooks    []Hook
	mutation *ServiceVersionMutation
}

// Where appends a list predicates to the ServiceVersionDelete builder.
func (svd *ServiceVersionDelete) Where(ps ...predicate.ServiceVersion) *ServiceVersionDelete {
	svd.mutation.Where(ps...)
	return svd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (svd *ServiceVersionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(svd.hooks) == 0 {
		affected, err = svd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceVersionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			svd.mutation = mutation
			affected, err = svd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(svd.hooks) - 1; i >= 0; i-- {
			if svd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = svd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, svd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (svd *ServiceVersionDelete) ExecX(ctx context.Context) int {
	n, err := svd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (svd *ServiceVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: serviceversion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: serviceversion.FieldID,
			},
		},
	}
	if ps := svd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, svd.driver, _spec)
}

// ServiceVersionDeleteOne is the builder for deleting a single ServiceVersion entity.
type ServiceVersionDeleteOne struct {
	svd *ServiceVersionDelete
}

// Exec executes the deletion query.
func (svdo *ServiceVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := svdo.svd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{serviceversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (svdo *ServiceVersionDeleteOne) ExecX(ctx context.Context) {
	svdo.svd.ExecX(ctx)
}
