// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"entproject/ent/service"
	"entproject/ent/serviceversion"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ServiceVersionCreate is the builder for creating a ServiceVersion entity.
type ServiceVersionCreate struct {
	config
	mutation *ServiceVersionMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (svc *ServiceVersionCreate) SetVersion(i int) *ServiceVersionCreate {
	svc.mutation.SetVersion(i)
	return svc
}

// SetConfig sets the "config" field.
func (svc *ServiceVersionCreate) SetConfig(s string) *ServiceVersionCreate {
	svc.mutation.SetConfig(s)
	return svc
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (svc *ServiceVersionCreate) SetServiceID(id uuid.UUID) *ServiceVersionCreate {
	svc.mutation.SetServiceID(id)
	return svc
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (svc *ServiceVersionCreate) SetNillableServiceID(id *uuid.UUID) *ServiceVersionCreate {
	if id != nil {
		svc = svc.SetServiceID(*id)
	}
	return svc
}

// SetService sets the "service" edge to the Service entity.
func (svc *ServiceVersionCreate) SetService(s *Service) *ServiceVersionCreate {
	return svc.SetServiceID(s.ID)
}

// Mutation returns the ServiceVersionMutation object of the builder.
func (svc *ServiceVersionCreate) Mutation() *ServiceVersionMutation {
	return svc.mutation
}

// Save creates the ServiceVersion in the database.
func (svc *ServiceVersionCreate) Save(ctx context.Context) (*ServiceVersion, error) {
	var (
		err  error
		node *ServiceVersion
	)
	if len(svc.hooks) == 0 {
		if err = svc.check(); err != nil {
			return nil, err
		}
		node, err = svc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceVersionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = svc.check(); err != nil {
				return nil, err
			}
			svc.mutation = mutation
			if node, err = svc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(svc.hooks) - 1; i >= 0; i-- {
			if svc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = svc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, svc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (svc *ServiceVersionCreate) SaveX(ctx context.Context) *ServiceVersion {
	v, err := svc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (svc *ServiceVersionCreate) Exec(ctx context.Context) error {
	_, err := svc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (svc *ServiceVersionCreate) ExecX(ctx context.Context) {
	if err := svc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (svc *ServiceVersionCreate) check() error {
	if _, ok := svc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ServiceVersion.version"`)}
	}
	if _, ok := svc.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "ServiceVersion.config"`)}
	}
	return nil
}

func (svc *ServiceVersionCreate) sqlSave(ctx context.Context) (*ServiceVersion, error) {
	_node, _spec := svc.createSpec()
	if err := sqlgraph.CreateNode(ctx, svc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (svc *ServiceVersionCreate) createSpec() (*ServiceVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceVersion{config: svc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: serviceversion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: serviceversion.FieldID,
			},
		}
	)
	if value, ok := svc.mutation.Version(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: serviceversion.FieldVersion,
		})
		_node.Version = value
	}
	if value, ok := svc.mutation.Config(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: serviceversion.FieldConfig,
		})
		_node.Config = value
	}
	if nodes := svc.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceversion.ServiceTable,
			Columns: []string{serviceversion.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: service.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.service_service_versions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServiceVersionCreateBulk is the builder for creating many ServiceVersion entities in bulk.
type ServiceVersionCreateBulk struct {
	config
	builders []*ServiceVersionCreate
}

// Save creates the ServiceVersion entities in the database.
func (svcb *ServiceVersionCreateBulk) Save(ctx context.Context) ([]*ServiceVersion, error) {
	specs := make([]*sqlgraph.CreateSpec, len(svcb.builders))
	nodes := make([]*ServiceVersion, len(svcb.builders))
	mutators := make([]Mutator, len(svcb.builders))
	for i := range svcb.builders {
		func(i int, root context.Context) {
			builder := svcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, svcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, svcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, svcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (svcb *ServiceVersionCreateBulk) SaveX(ctx context.Context) []*ServiceVersion {
	v, err := svcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (svcb *ServiceVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := svcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (svcb *ServiceVersionCreateBulk) ExecX(ctx context.Context) {
	if err := svcb.Exec(ctx); err != nil {
		panic(err)
	}
}
